# Generated by Django 3.2.4 on 2023-09-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dyoueyepq/image/upload/v1694384209/samples/default_profile_zoafup.jpg', upload_to='images/'),
        ),
    ]
